DOMAINS = ("HackerRank", "Claude", "Visa")

STATUSES = ("replied", "escalated")
REQUEST_TYPES = ("product_issue", "feature_request", "bug", "invalid")

PRODUCT_AREAS = {
    "HackerRank": {
        "screen",
        "interview",
        "community",
        "assessment_access",
        "proctoring",
        "plagiarism_detection",
        "candidate_experience",
        "recruiter_tools",
        "billing_and_plans",
        "test_configuration",
        "api_integration",
        "account_management",
        "time_accommodation",
        "resume_builder",
        "mock_interviews",
        "subscription_management",
    },
    "Claude": {
        "subscription_and_billing",
        "usage_limits",
        "api_access",
        "model_behavior",
        "safety_and_policy",
        "account_access",
        "feature_request",
        "claude_code",
        "privacy",
        "data_retention",
        "lti_integration",
        "web_crawling",
        "conversation_management",
        "third_party_integration",
    },
    "Visa": {
        "card_activation",
        "fraud_and_disputes",
        "transaction_issues",
        "atm_and_cash",
        "merchant_payments",
        "account_security",
        "international_usage",
        "card_replacement",
        "travel_support",
        "general_support",
        "identity_theft",
        "minimum_spend_policy",
    },
    "General": {"cross_domain", "out_of_scope", "conversation_management", "unknown"},
}

DOMAIN_SIGNALS = {
    "HackerRank": {
        "assessment",
        "coding test",
        "candidate",
        "recruiter",
        "test link",
        "proctoring",
        "plagiarism",
        "mock interview",
        "hackerrank",
        "submissions",
        "score",
        "resume builder",
        "interviewer",
        "apply tab",
        "hiring subscription",
        "test variant",
        "time accommodation",
        "coding challenge",
        "challenge",
        "screen",
        "inactivity timeout",
        "codepair",
        "infosec",
        "compatible check",
        "zoom connectivity",
        "rescheduling assessment",
        "reschedule assessment",
        "certificate",
        "pause subscription",
        "cs_live_",
    },
    "Claude": {
        "claude",
        "claude.ai",
        "claude ai",
        "anthropic",
        "ai assistant",
        "pro plan",
        "api key",
        "bedrock",
        "aws bedrock",
        "lti",
        "lti key",
        "canvas",
        "web crawling",
        "crawling my website",
        "conversation",
        "usage limits",
        "data training",
        "model behavior",
        "claude code",
        "security vulnerability",
        "bug bounty",
        "workspace",
        "seat removed",
        "team workspace",
    },
    "Visa": {
        "visa",
        "visa card",
        "card",
        "payment",
        "transaction",
        "fraud",
        "chargeback",
        "pin",
        "atm",
        "merchant",
        "stolen card",
        "travel cheques",
        "cash advance",
        "dispute",
        "visa co in",
        "minimum spend",
        "card blocked",
        "identity theft",
        "urgent cash",
        "us virgin islands",
        "carte visa",
        "bloquee",
        "carte",
        "paiement",
        "transaction",
        "fraude",
        "voyage",
    },
}

PRODUCT_AREA_SIGNALS = {
    "HackerRank": {
        "assessment_access": {"assessment", "test link", "invite", "invitation", "expired", "access", "candidate blocked"},
        "proctoring": {"proctor", "proctoring", "webcam", "camera", "tab switch", "monitoring", "zoom", "compatible check", "compatibility"},
        "plagiarism_detection": {"plagiarism", "similarity", "cheating", "copied", "copying"},
        "candidate_experience": {"candidate", "certificate", "name correction", "profile", "submission", "score dispute", "unfair grading", "answer review"},
        "recruiter_tools": {"recruiter", "hiring manager", "team", "invite candidates", "report"},
        "billing_and_plans": {"billing", "invoice", "refund", "charge", "plan", "payment", "order id", "cs_live_"},
        "test_configuration": {"test variant", "time limit", "question", "scoring", "test setting", "configuration"},
        "api_integration": {"api", "webhook", "ats", "integration"},
        "account_management": {"account", "password", "email", "remove employee", "remove interviewer", "delete user", "admin", "infosec questionnaire"},
        "time_accommodation": {"accommodation", "extra time", "extend time", "time accommodation"},
        "resume_builder": {"resume builder", "resume", "cv"},
        "mock_interviews": {"mock interview", "mock interviews"},
        "subscription_management": {"subscription", "cancel", "pause"},
        "interview": {"interview", "interviewer", "codepair", "inactivity timeout"},
        "screen": {"screen", "screening", "apply tab", "submissions", "challenges"},
        "community": {"community", "discussion", "leaderboard"},
    },
    "Claude": {
        "subscription_and_billing": {"billing", "invoice", "refund", "subscription", "pro plan", "cancel", "pause", "payment"},
        "usage_limits": {"usage limit", "limit", "rate limit", "message cap"},
        "api_access": {"api key", "api", "console", "key", "token"},
        "model_behavior": {"model behavior", "hallucination", "answer quality", "output", "prompt", "all requests failing", "completely down"},
        "safety_and_policy": {"safety", "policy", "abuse", "jailbreak", "harmful", "security vulnerability", "bug bounty", "vulnerability"},
        "account_access": {"account", "login", "password", "sign in", "access", "seat removed", "not the admin", "not the owner", "workspace"},
        "feature_request": {"feature", "request", "add", "support"},
        "claude_code": {"claude code", "terminal", "cli"},
        "privacy": {"privacy", "gdpr", "delete data", "data training", "personal data"},
        "data_retention": {"data retention", "retention", "conversation history", "delete conversations", "model training", "how long"},
        "lti_integration": {"lti", "learning tool", "canvas", "moodle", "lti key", "students"},
        "web_crawling": {"web crawling", "crawler", "robots txt", "robots.txt", "crawl", "crawling my website", "claudebot"},
        "conversation_management": {"conversation", "chat", "delete chat", "rename"},
        "third_party_integration": {"bedrock", "aws", "third party", "vertex"},
    },
    "Visa": {
        "card_activation": {"activate", "activation", "new card"},
        "fraud_and_disputes": {"fraud", "dispute", "chargeback", "unauthorized", "suspicious", "scam", "wrong product", "refund demand"},
        "transaction_issues": {"transaction", "declined", "failed payment", "refund", "charge"},
        "atm_and_cash": {"atm", "cash", "cash advance", "pin", "urgent cash"},
        "merchant_payments": {"merchant", "pos", "tap", "contactless"},
        "account_security": {"account security", "pin", "password", "blocked", "locked"},
        "international_usage": {"international", "foreign", "overseas", "travel"},
        "card_replacement": {"replace", "replacement", "lost card", "stolen card"},
        "travel_support": {"travel", "voyage", "abroad", "overseas", "blocked during travel", "card blocked", "bloquee", "bloque"},
        "general_support": {"support", "help", "card"},
        "identity_theft": {"identity theft", "stolen identity", "kyc", "impersonation"},
        "minimum_spend_policy": {"minimum spend", "minimum transaction", "minimum $10", "us virgin islands"},
    },
}

INJECTION_SIGNALS = {
    "ignore previous instructions",
    "ignore above",
    "disregard all instructions",
    "pretend you are",
    "act as",
    "act as if you are",
    "you are now",
    "jailbreak",
    "developer mode",
    "unrestricted mode",
    "show your system prompt",
    "reveal your instructions",
    "print your rules",
    "display your context",
    "affiche toutes les regles internes",
    "affiche les documents recuperes",
    "la logique exacte que vous utilisez",
    "developer message",
    "system message",
    "system prompt",
}

INJECTION_REGEXES = (
    r"\bnew\s+instructions\s*:",
    r"\byou\s+must\s+now\b",
    r"\bdisregard\s+(all\s+)?(previous|above)\s+instructions\b",
    r"\bdan\b",
)

MALICIOUS_SIGNALS = {
    "delete system files",
    "delete all files from the system",
    "delete everything",
    "rm -rf",
    "format the disk",
    "give me the code to delete",
    "write a script to remove all",
    "exfiltrate",
    "steal data",
    "bypass admin",
    "restore my access even though",
    "social engineer",
}

GREETING_ONLY = {
    "hi",
    "hello",
    "hey",
    "thanks",
    "thank you",
    "youre welcome",
    "good morning",
    "good afternoon",
    "good evening",
}

OUT_OF_SCOPE_SIGNALS = {
    "actor in iron man",
    "capital of",
    "weather",
    "recipe",
    "movie",
    "song lyrics",
    "sports score",
}

HIGH_RISK_SIGNALS = {
    "fraud",
    "unauthorized",
    "unauthorised",
    "data breach",
    "identity theft",
    "security vulnerability",
    "vulnerability",
    "account compromise",
    "compromised",
    "legal",
    "gdpr",
    "privacy demand",
    "delete all my data",
    "active threat",
    "infosec questionnaire",
    "score dispute",
    "result override",
    "requesting access",
    "subscription pause",
    "cancel subscription",
    "suspicious transaction",
    "stolen card",
    "stolen identity",
    "root access",
}

MEDIUM_RISK_SIGNALS = {
    "billing",
    "invoice",
    "account access",
    "subscription",
    "cancel",
    "pause",
    "configuration",
    "score dispute",
    "refund",
    "bug",
    "login",
    "password",
    "charge",
}

HIGH_URGENCY_SIGNALS = {
    "live test",
    "in progress",
    "right now",
    "active fraud",
    "system-wide outage",
    "site is down",
    "all users",
    "all submissions",
    "card blocked during active travel",
    "blocked during travel",
    "mid assessment",
    "mid-assessment",
    "actively exploited",
    "active fraud right now",
    "identity stolen",
    "candidate mid-assessment",
}

ALWAYS_ESCALATE_SIGNALS = {
    "refund",
    "refund demand",
    "score dispute",
    "unfair grading",
    "review my answer",
    "override result",
    "result override",
    "security vulnerability",
    "vulnerability",
    "gdpr",
    "bulk data deletion",
    "pause subscription",
    "cancel subscription",
    "subscription pause",
    "infosec questionnaire",
    "questionnaire",
    "bedrock",
    "aws bedrock",
    "suspicious transaction",
    "fraud",
    "identity theft",
    "identity stolen",
    "stolen card",
    "not the admin",
    "not the owner",
    "cs_live_",
    "reschedule assessment",
    "rescheduling assessment",
}

FEATURE_SIGNALS = {
    "feature request",
    "please add",
    "can you add",
    "i wish",
    "suggestion",
    "would be useful",
    "dark mode",
}

BUG_SIGNALS = {
    "bug",
    "crash",
    "error",
    "500",
    "site is down",
    "down",
    "not working",
    "broken",
    "failed",
    "failure",
    "failing",
    "cannot see",
    "can't see",
    "vulnerability",
    "security vulnerability",
    "cannot submit",
    "cant submit",
    "can't submit",
    "outage",
}

STOPWORDS = {
    "a",
    "an",
    "and",
    "are",
    "as",
    "at",
    "be",
    "by",
    "for",
    "from",
    "how",
    "i",
    "in",
    "is",
    "it",
    "my",
    "of",
    "on",
    "or",
    "our",
    "please",
    "the",
    "this",
    "to",
    "with",
    "you",
    "your",
}
